[package]
name = "azure-mqtt"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]

[dependencies]
mqtt-protocol = "*"
native-tls = "*"
clap = "*"
toml = "*"
serde = "*"
serde_derive = "*"